package gov.epa.exp_data_gathering.parse.Burkhard;

import java.util.Vector;

import com.google.gson.JsonObject;

import gov.epa.api.ExperimentalConstants;
import gov.epa.exp_data_gathering.parse.ExcelSourceReader;

public class RecordBurkhard {
	public String Chemical;
	public String CAS;
	public String Abbreviation;
	public String Log_BCF_Steady_State;
	public String field4;
	public String field5;
	public String field6;
	public String Log_BCF_Kinetic;
	public String field8;
	public String field9;
	public String field10;
	public String Log_BAF;
	public String field12;
	public String field13;
	public String field14;
	public String Measured_Trophic_Level;
	public String field16;
	public String field17;
	public String Estimated_Trophic_Level;
	public String Common_Name;
	public String Species_Latin_Name;
	public String Species_Weight_g;
	public String field22;
	public String Tissue;
	public String Location;
	public String Reference;
	public String BCF_data;
	public String OECD_305;
	public String ku;
	public String ku_sd;
	public String field30;
	public String days_of_uptake;
	public String ke;
	public String ke_sd;
	public String field34;
	public String days_of_elimination;
	public String half_life_days;
	public String half_life_sd_days;
	public String SS;
	public String Kinetic;
	public String Modeled;
	public String Exposure_Concentrations;
	public String Study_Quality_BCF;
	public String Comments_BCF;
	public String k_dietary;
	public String k_dietary_sd;
	public String field46;
	public String Assimulation_Efficiency;
	public String Assimulation_Efficiency_SD;
	public String field49;
	public String BAF;
	public String of_water_samples;
	public String start_date;
	public String end_date;
	public String field54;
	public String of_biota_samples;
	public String start_date;
	public String end_date;
	public String Average_weight_g;
	public String Average_Length_cm;
	public String Sex_F_M;
	public String Average_Age;
	public String Age_sd;
	public String General_experimental_design;
	public String Water_Biota_spatial_coordination;
	public String Water_Biota_temporal_coordination;
	public String Number_Biota_Samples;
	public String Number_of_Water;
	public String Study_Quality_BAF;
	public String Comments_BAFs;
	public String field70;
	public String Mixture_Exposure;
	public String Concentration_in_Biota;
	public String sd;
	public String units;
	public String MDL;
	public String Comments_Biota_Samples;
	public String Concentration_in_environmental_media;
	public String sd;
	public String units;
	public String MDL;
	public String Comments_Environmental_Media;
	public String field82;
	public String Organic_Carbon;
	public String sd;
	public String units;
	public String Comments_OC;
	public String field87;
	public String Marine_Brackish_Freshwater;
	public String Comments_Marine_Brackish_Freshwater;
	public String field90;
	public String Taxonomy_Name_Level;
	public String kingdom;
	public String phylum;
	public String class;
	public String order;
	public String family;
	public String genus;
	public String species;
	public String ITIS_TaxID;
	public String NCBI_TaxID;
	public String GBIF_TaxID;
	public String Common_Name_NCBI_ITIS;
	public String Taxomony_Name_Source;
	public static final String[] fieldNames = {"Chemical","CAS","Abbreviation","Log_BCF_Steady_State","field4","field5","field6","Log_BCF_Kinetic","field8","field9","field10","Log_BAF","field12","field13","field14","Measured_Trophic_Level","field16","field17","Estimated_Trophic_Level","Common_Name","Species_Latin_Name","Species_Weight_g","field22","Tissue","Location","Reference","BCF_data","OECD_305","ku","ku_sd","field30","days_of_uptake","ke","ke_sd","field34","days_of_elimination","half_life_days","half_life_sd_days","SS","Kinetic","Modeled","Exposure_Concentrations","Study_Quality_BCF","Comments_BCF","k_dietary","k_dietary_sd","field46","Assimulation_Efficiency","Assimulation_Efficiency_SD","field49","BAF","of_water_samples","start_date","end_date","field54","of_biota_samples","start_date","end_date","Average_weight_g","Average_Length_cm","Sex_F_M","Average_Age","Age_sd","General_experimental_design","Water_Biota_spatial_coordination","Water_Biota_temporal_coordination","Number_Biota_Samples","Number_of_Water","Study_Quality_BAF","Comments_BAFs","field70","Mixture_Exposure","Concentration_in_Biota","sd","units","MDL","Comments_Biota_Samples","Concentration_in_environmental_media","sd","units","MDL","Comments_Environmental_Media","field82","Organic_Carbon","sd","units","Comments_OC","field87","Marine_Brackish_Freshwater","Comments_Marine_Brackish_Freshwater","field90","Taxonomy_Name_Level","kingdom","phylum","class","order","family","genus","species","ITIS_TaxID","NCBI_TaxID","GBIF_TaxID","Common_Name_NCBI_ITIS","Taxomony_Name_Source"};

	public static final String lastUpdated = "04/09/2021";
	public static final String sourceName = ExperimentalConstants.strSourceBurkhard;

	private static final String fileName = "etc5010-sup-0002-data_bcf_baf_pfas.xlsx";

	public static Vector<JsonObject> parseBurkhardRecordsFromExcel() {
		ExcelSourceReader esr = new ExcelSourceReader(fileName, sourceName);
		Vector<JsonObject> records = esr.parseRecordsFromExcel(0);
		return records;
	}
}