package gov.epa.QSAR.DataSetCreation;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.text.StringEscapeUtils;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.ss.util.CellReference;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import gov.epa.api.ExperimentalConstants;
import gov.epa.exp_data_gathering.parse.ExperimentalRecord;
import gov.epa.exp_data_gathering.parse.ExperimentalRecords;
import gov.epa.exp_data_gathering.parse.ParseUtilities;

public class RecordQSAR {
	
	public String id_physchem;//	Autonumbered record number for physchem data (generated by database later)
	public String id_record_source;//	Record number for reference that the physchem data came from (generated by database later- may only need for records from journal articles)
	
	public boolean usable;
	public String reason;
	
	//ID fields:
	public String casrn;//Chemical abstracts service number (only if provided by the reference)
	public String einecs;
	public String chemical_name;//	Most systematic name (only if provided in the reference)
	public String smiles;//Simplified Molecular Input Line Entry System for molecular structure (only if provided in the reference)
	public String source_name;
	public String url;
	public String date_accessed;
	
	public String property_name;//	Name of the property (use  "options_property_names" lookup table to consistently populate the field)

	public Double property_value_point_estimate_exp;// Point estimate of the property (when a single value is given)
	public String property_value_units_exp;//The units for the property value (convert to defined values in ExperimentalConstants class)
	
	public Double property_value_point_estimate_qsar;// Point estimate of the property (when a single value is given)
	public String property_value_units_qsar;//The units for the property value (convert to defined values in ExperimentalConstants class)
	
	public String pressure_mmHg;
	public Double temperature_C;
	public String pH;
	
	//DSSTox fields:
	public String dsstox_substance_id; //DSSTox substance identifier
	public String Substance_Name;
	public String Substance_CASRN;
	public String Substance_Type;
	public String Substance_Note;
	public String Structure_SMILES;
	public String Structure_InChI;
	public String Structure_InChIKey;
	public String Structure_Formula;
	public Double Structure_MolWt;
	public String Structure_SMILES_2D_QSAR;
	public String Structure_InChIKey_QSAR_Ready;
	public String Structure_InChIKey1_QSAR_Ready;
	public String comboID;
	
	public final static String [] outputFieldNames = {"id_physchem",
			"usable",
			"reason",			
			"casrn",
			"einecs",
			"chemical_name",
			"smiles", 
			"dsstox_substance_id",
			"Substance_Name", "Substance_CASRN", "Substance_Type", "Substance_Note", "Structure_SMILES",
			"Structure_InChI", "Structure_InChIKey", "Structure_Formula", "Structure_MolWt", "Structure_SMILES_2D_QSAR",
			"Structure_InChIKey_QSAR_Ready", "Structure_InChIKey1_QSAR_Ready",			
			"property_value_point_estimate_exp",
			"property_value_units_exp",
			"property_value_point_estimate_qsar",
			"property_value_units_qsar",
			"pressure_mmHg",
			"temperature_C",
			"pH",
			"url",
			"date_accessed"};
	
	
	public RecordQSAR (ExperimentalRecord er) {
		
		usable = true;
		
		id_physchem = er.id_physchem;
		id_record_source = er.id_record_source;
		
		casrn = er.casrn;
		einecs = er.einecs;
		chemical_name = er.chemical_name;
		smiles = er.smiles;
		dsstox_substance_id = er.dsstox_substance_id;
		source_name = er.source_name;
		url = er.url;
		date_accessed = er.date_accessed;
		property_name = er.property_name;
		pressure_mmHg = er.pressure_mmHg;
		temperature_C = er.temperature_C;
		pH = er.pH;
		
		property_value_units_exp = er.property_value_units_final;
		property_value_point_estimate_exp = er.property_value_point_estimate_final==null ? er.rangeAverage() : er.property_value_point_estimate_final;
		
		
	}
	
	public void setComboID(String del) {
		String CAS=casrn;
		if (CAS==null || CAS.trim().isEmpty()) CAS="casrn=null";//need placeholder so dont get spurious match in chemreg
		else {
			CAS=ParseUtilities.fixCASLeadingZero(CAS);
		}
		String name=StringEscapeUtils.escapeJava(chemical_name);
		
		String EINECS=einecs;
		if (EINECS==null || EINECS.trim().isEmpty()) EINECS="einecs=null";//need placeholder so dont get spurious match in chemreg
		EINECS=EINECS.trim();
		
		if (name==null || name.trim().isEmpty()) name="name=null";//need placeholder so dont get spurious match in chemreg
		name=name.trim();
		

		String SMILES=smiles;
		if (SMILES==null || SMILES.trim().isEmpty()) SMILES="smiles=null";//need placeholder so dont get spurious match in chemreg
		SMILES=SMILES.trim();
		
		//TODO omit chemicals where smiles indicates bad element....
		
		comboID=CAS+del+EINECS+del+name+del+SMILES;
		
	}
	
	public void assignValue(String fieldName,String fieldValue) {
		if (fieldValue.isEmpty()) return;
		Field myField;
		try {
			myField = getClass().getDeclaredField(fieldName);
			if (myField.getType().getName().contentEquals("boolean")) {
				myField.setBoolean(this, Boolean.parseBoolean(fieldValue));
			} else if (myField.getType().getName().contentEquals("double")) {
				myField.setDouble(this, Double.parseDouble(fieldValue));
			} else if (myField.getType().getName().contentEquals("int")) {
				myField.setInt(this, Integer.parseInt(fieldValue));
			} else if (myField.getType().getName().contentEquals("java.lang.Double")) {
				Double dval=Double.parseDouble(fieldValue);						
				myField.set(this, dval);
			} else if (myField.getType().getName().contentEquals("java.lang.Integer")) {
				Integer ival=Integer.parseInt(fieldValue);
				myField.setInt(this,ival);
			} else if (myField.getType().getName().contentEquals("java.lang.String")) {
				myField.set(this, fieldValue);
			} else {
				System.out.println("Need to implement"+myField.getType().getName());
			}					
		} catch (Exception e) {
			e.printStackTrace();
		} 
	}
	
	
}
