package gov.epa.ghs_data_gathering.Parse.CERAPP_EXP;

import java.util.HashMap;
import java.util.Vector;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

import gov.epa.api.ExperimentalConstants;
import gov.epa.api.ScoreRecord;
import gov.epa.exp_data_gathering.parse.ExcelSourceReader;
import gov.epa.ghs_data_gathering.Parse.ParseSIN;

public class RecordCERAPP_Exp {
	public String CODE;
	public String CASRN;
	public String Name;
	public String DSSTox_GSID;
	public String target_gene;
	public String use_category;
	public String use_super_category;
	public String structure_category;
	public String structure_super_category;
	public String Phase_I;
	public String Phase_II;
	public String E1K;
	public String Tox21;
	public String EDSP_Universe;
	public String cytotox_median_um;
	public String cytotox_lower_bound_um;
	public String cytotox_assays_hit;
	public String AUC_Agonist;
	public String AUC_Agonist_alphamin;
	public String AUC_Agonist_alphamax;
	public String AUC_Antagonist;
	public String AUC_Antagonist_alphamin;
	public String AUC_Antagonist_alphamax;
	public String AUC_R3;
	public String AUC_R4;
	public String AUC_R5;
	public String AUC_R6;
	public String AUC_R7;
	public String AUC_R8;
	public String AUC_R9;
	public String AUC_A1;
	public String AUC_A2;
	public String AUC_A3;
	public String AUC_A4;
	public String AUC_A5;
	public String AUC_A6;
	public String AUC_A7;
	public String AUC_A8;
	public String AUC_A9;
	public String AUC_A10;
	public String AUC_A11;
	public String AUC_A12;
	public String AUC_A13;
	public String AUC_A14;
	public String AUC_A15;
	public String AUC_A17;
	public String AUC_A18;
	public String NVS_NR_bER_AC50;
	public String NVS_NR_hER_AC50;
	public String NVS_NR_mERa_AC50;
	public String OT_ER_ERaERa_0480_AC50;
	public String OT_ER_ERaERa_1440_AC50;
	public String OT_ER_ERaERb_0480_AC50;
	public String OT_ER_ERaERb_1440_AC50;
	public String OT_ER_ERbERb_0480_AC50;
	public String OT_ER_ERbERb_1440_AC50;
	public String OT_ERa_EREGFP_0120_AC50;
	public String OT_ERa_EREGFP_0480_AC50;
	public String ATG_ERa_TRANS_up_AC50;
	public String ATG_ERE_CIS_up_AC50;
	public String Tox21_ERa_BLA_Agonist_ratio_AC50;
	public String Tox21_ERa_LUC_BG1_Agonist_AC50;
	public String ACEA_T47D_80hr_Positive_AC50;
	public String Tox21_ERa_BLA_Antagonist_ratio_AC50;
	public String Tox21_ERa_LUC_BG1_Antagonist_AC50;
	public String NVS_NR_bER_Emax;
	public String NVS_NR_hER_Emax;
	public String NVS_NR_mERa_Emax;
	public String OT_ER_ERaERa_0480_Emax;
	public String OT_ER_ERaERa_1440_Emax;
	public String OT_ER_ERaERb_0480_Emax;
	public String OT_ER_ERaERb_1440_Emax;
	public String OT_ER_ERbERb_0480_Emax;
	public String OT_ER_ERbERb_1440_Emax;
	public String OT_ERa_EREGFP_0120_Emax;
	public String OT_ERa_EREGFP_0480_Emax;
	public String ATG_ERa_TRANS_up_Emax;
	public String ATG_ERE_CIS_up_Emax;
	public String Tox21_ERa_BLA_Agonist_ratio_Emax;
	public String Tox21_ERa_LUC_BG1_Agonist_Emax;
	public String ACEA_T47D_80hr_Positive_Emax;
	public String Tox21_ERa_BLA_Antagonist_ratio_Emax;
	public String Tox21_ERa_LUC_BG1_Antagonist_Emax;
	public String NVS_NR_bER_T;
	public String NVS_NR_hER_T;
	public String NVS_NR_mERa_T;
	public String OT_ER_ERaERa_0480_T;
	public String OT_ER_ERaERa_1440_T;
	public String OT_ER_ERaERb_0480_T;
	public String OT_ER_ERaERb_1440_T;
	public String OT_ER_ERbERb_0480_T;
	public String OT_ER_ERbERb_1440_T;
	public String OT_ERa_EREGFP_0120_T;
	public String OT_ERa_EREGFP_0480_T;
	public String ATG_ERa_TRANS_up_T;
	public String ATG_ERE_CIS_up_T;
	public String Tox21_ERa_BLA_Agonist_ratio_T;
	public String Tox21_ERa_LUC_BG1_Agonist_T;
	public String ACEA_T47D_80hr_Positive_T;
	public String Tox21_ERa_BLA_Antagonist_ratio_T;
	public String Tox21_ERa_LUC_BG1_Antagonist_T;
	public String NVS_NR_bER_W;
	public String NVS_NR_hER_W;
	public String NVS_NR_mERa_W;
	public String OT_ER_ERaERa_0480_W;
	public String OT_ER_ERaERa_1440_W;
	public String OT_ER_ERaERb_0480_W;
	public String OT_ER_ERaERb_1440_W;
	public String OT_ER_ERbERb_0480_W;
	public String OT_ER_ERbERb_1440_W;
	public String OT_ERa_EREGFP_0120_W;
	public String OT_ERa_EREGFP_0480_W;
	public String ATG_ERa_TRANS_up_W;
	public String ATG_ERE_CIS_up_W;
	public String Tox21_ERa_BLA_Agonist_ratio_W;
	public String Tox21_ERa_LUC_BG1_Agonist_W;
	public String ACEA_T47D_80hr_Positive_W;
	public String Tox21_ERa_BLA_Antagonist_ratio_W;
	public String Tox21_ERa_LUC_BG1_Antagonist_W;
	public String NVS_NR_bER_Zscore;
	public String NVS_NR_hER_Zscore;
	public String NVS_NR_mERa_Zscore;
	public String OT_ER_ERaERa_0480_Zscore;
	public String OT_ER_ERaERa_1440_Zscore;
	public String OT_ER_ERaERb_0480_Zscore;
	public String OT_ER_ERaERb_1440_Zscore;
	public String OT_ER_ERbERb_0480_Zscore;
	public String OT_ER_ERbERb_1440_Zscore;
	public String OT_ERa_EREGFP_0120_Zscore;
	public String OT_ERa_EREGFP_0480_Zscore;
	public String ATG_ERa_TRANS_up_Zscore;
	public String ATG_ERE_CIS_up_Zscore;
	public String Tox21_ERa_BLA_Agonist_ratio_Zscore;
	public String Tox21_ERa_LUC_BG1_Agonist_Zscore;
	public String ACEA_T47D_80hr_Positive_Zscore;
	public String Tox21_ERa_BLA_Antagonist_ratio_Zscore;
	public String Tox21_ERa_LUC_BG1_Antagonist_Zscore;
	public String NVS_NR_bER_maxConc;
	public String NVS_NR_hER_maxConc;
	public String NVS_NR_mERa_maxConc;
	public String OT_ER_ERaERa_0480_maxConc;
	public String OT_ER_ERaERa_1440_maxConc;
	public String OT_ER_ERaERb_0480_maxConc;
	public String OT_ER_ERaERb_1440_maxConc;
	public String OT_ER_ERbERb_0480_maxConc;
	public String OT_ER_ERbERb_1440_maxConc;
	public String OT_ERa_EREGFP_0120_maxConc;
	public String OT_ERa_EREGFP_0480_maxConc;
	public String ATG_ERa_TRANS_up_maxConc;
	public String ATG_ERE_CIS_up_maxConc;
	public String Tox21_ERa_BLA_Agonist_ratio_maxConc;
	public String Tox21_ERa_LUC_BG1_Agonist_maxConc;
	public String ACEA_T47D_80hr_Positive_maxConc;
	public String Tox21_ERa_BLA_Antagonist_ratio_maxConc;
	public String Tox21_ERa_LUC_BG1_Antagonist_maxConc;
	public String NVS_NR_bER_AC10;
	public String NVS_NR_hER_AC10;
	public String NVS_NR_mERa_AC10;
	public String OT_ER_ERaERa_0480_AC10;
	public String OT_ER_ERaERa_1440_AC10;
	public String OT_ER_ERaERb_0480_AC10;
	public String OT_ER_ERaERb_1440_AC10;
	public String OT_ER_ERbERb_0480_AC10;
	public String OT_ER_ERbERb_1440_AC10;
	public String OT_ERa_EREGFP_0120_AC10;
	public String OT_ERa_EREGFP_0480_AC10;
	public String ATG_ERa_TRANS_up_AC10;
	public String ATG_ERE_CIS_up_AC10;
	public String Tox21_ERa_BLA_Agonist_ratio_AC10;
	public String Tox21_ERa_LUC_BG1_Agonist_AC10;
	public String ACEA_T47D_80hr_Positive_AC10;
	public String Tox21_ERa_BLA_Antagonist_ratio_AC10;
	public String Tox21_ERa_LUC_BG1_Antagonist_AC10;
	public String NVS_NR_bER_ACC;
	public String NVS_NR_hER_ACC;
	public String NVS_NR_mERa_ACC;
	public String OT_ER_ERaERa_0480_ACC;
	public String OT_ER_ERaERa_1440_ACC;
	public String OT_ER_ERaERb_0480_ACC;
	public String OT_ER_ERaERb_1440_ACC;
	public String OT_ER_ERbERb_0480_ACC;
	public String OT_ER_ERbERb_1440_ACC;
	public String OT_ERa_EREGFP_0120_ACC;
	public String OT_ERa_EREGFP_0480_ACC;
	public String ATG_ERa_TRANS_up_ACC;
	public String ATG_ERE_CIS_up_ACC;
	public String Tox21_ERa_BLA_Agonist_ratio_ACC;
	public String Tox21_ERa_LUC_BG1_Agonist_ACC;
	public String ACEA_T47D_80hr_Positive_ACC;
	public String Tox21_ERa_BLA_Antagonist_ratio_ACC;
	public String Tox21_ERa_LUC_BG1_Antagonist_ACC;
	public String NVS_NR_bER_ACB;
	public String NVS_NR_hER_ACB;
	public String NVS_NR_mERa_ACB;
	public String OT_ER_ERaERa_0480_ACB;
	public String OT_ER_ERaERa_1440_ACB;
	public String OT_ER_ERaERb_0480_ACB;
	public String OT_ER_ERaERb_1440_ACB;
	public String OT_ER_ERbERb_0480_ACB;
	public String OT_ER_ERbERb_1440_ACB;
	public String OT_ERa_EREGFP_0120_ACB;
	public String OT_ERa_EREGFP_0480_ACB;
	public String ATG_ERa_TRANS_up_ACB;
	public String ATG_ERE_CIS_up_ACB;
	public String Tox21_ERa_BLA_Agonist_ratio_ACB;
	public String Tox21_ERa_LUC_BG1_Agonist_ACB;
	public String ACEA_T47D_80hr_Positive_ACB;
	public String Tox21_ERa_BLA_Antagonist_ratio_ACB;
	public String Tox21_ERa_LUC_BG1_Antagonist_ACB;
	public String NVS_NR_bER_flags;
	public String NVS_NR_hER_flags;
	public String NVS_NR_mERa_flags;
	public String OT_ER_ERaERa_0480_flags;
	public String OT_ER_ERaERa_1440_flags;
	public String OT_ER_ERaERb_0480_flags;
	public String OT_ER_ERaERb_1440_flags;
	public String OT_ER_ERbERb_0480_flags;
	public String OT_ER_ERbERb_1440_flags;
	public String OT_ERa_EREGFP_0120_flags;
	public String OT_ERa_EREGFP_0480_flags;
	public String ATG_ERa_TRANS_up_flags;
	public String ATG_ERE_CIS_up_flags;
	public String Tox21_ERa_BLA_Agonist_ratio_flags;
	public String Tox21_ERa_LUC_BG1_Agonist_flags;
	public String ACEA_T47D_80hr_Positive_flags;
	public String Tox21_ERa_BLA_Antagonist_ratio_flags;
	public String Tox21_ERa_LUC_BG1_Antagonist_flags;
	public String pseudo_AC50_median;
	public String pseudo_AC50_min;
	public String AC50_spread;
	public String pseudo_AC10_median;
	public String pseudo_AC10_min;
	public String pseudo_ACC_median;
	public String pseudo_ACC_min;
	public String pseudo_ACB_median;
	public String pseudo_ACB_min;
	public String maximum_receptor;
	public String EAS_R1;
	public String EAS_R1_Class;
	public String EAS_R2;
	public String EAS_R2_Class;
	public String N_assays_tested;
	public String N_assays_hit;
	public String N_assays_hit_hi_Z;
	public String N_assays_hit_lo_Z;
	public String promiscuity_hi_Z;
	public String promiscuity_lo_Z;
	public String median_T;
	public String median_Z;
	public String Lit_N_Binding;
	public String Lit_N_Agonist;
	public String Lit_N_Antagonist;
	public String Lit_Hit_Binding;
	public String Lit_Hit_Agonist;
	public String Lit_Hit_Antagonist;
	public String ATG_nonER_hits_HIZ_TRANS;
	public String ATG_nonER_hits_HIZ_CIS;
	public String NVS_nonER_hits_HIZ;
	public String Tox21_BLA_Agonist_nonER_hits_HIZ;
	public String Tox21_BLA_Antagonist_nonER_hits_HIZ;
	public String Tox21_LUC_Agonist_nonER_hits_HIZ;
	public String Tox21_LUC_Antagonist_nonER_hits_HIZ;
	public String mol_MW;
	public String dipole;
	public String SASA;
	public String FOSA;
	public String FISA;
	public String PISA;
	public String WPSA;
	public String volume;
	public String donorHB;
	public String accptHB;
	public String dip_2_V;
	public String ACxDN_5_SA;
	public String glob;
	public String QPpolrz;
	public String QPlogPC16;
	public String QPlogPoct;
	public String QPlogPw;
	public String QPlogPo_w;
	public String QPlogS;
	public String CIQPlogS;
	public String QPlogHERG;
	public String QPPCaco;
	public String QPlogBB;
	public String QPPMDCK;
	public String QPlogKp;
	public String IP_eV;
	public String EA_eV;
	public String X_metab;
	public String QPlogKhsa;
	public String HumanOralAbsorption;
	public String PercentHumanOralAbsorption;
	public String SAfluorine;
	public String SAamideO;
	public String PSA;
	public String RuleOfFive;
	public String RuleOfThree;
	public String Molecular_weight;
	public String passesRuleOfThree;
	public String species;
	public String numRo5Violations;
	public String rotatableBonds;
	public String molecularWeight;
	public String alogp;
	public String acdAcidicPka;
	public String acdBasicPka;
	public String acdLogp;
	public String acdLogd;
	public String AM1_dipole;
	public String AM1_HOMO;
	public String AM1_LUMO;
	public String electrophilicity_index;
	public String DFT_IP;
	public String DFT_EA;
	public String DFT_electron_negativity;
	public String DFT_hardness;
	public String DFT_electrophilicity;
	public String DFT_donatingpower;
	public String DFT_acceptingpower;
	public String DFT_dipole;
	public String DFT_polarizability;
	public String DFT_aqueous_electron_affnity;
	public String DFT_HOMO;
	public String DFT_LUMO;
	public String Charged;

	public static final String[] fieldNames = {"CODE","CASRN","Name","DSSTox_GSID","target_gene","use_category","use_super_category","structure_category","structure_super_category","Phase_I","Phase_II","E1K","Tox21","EDSP_Universe","cytotox_median_um","cytotox_lower_bound_um","cytotox_assays_hit","AUC_Agonist","AUC_Agonist_alphamin","AUC_Agonist_alphamax","AUC_Antagonist","AUC_Antagonist_alphamin","AUC_Antagonist_alphamax","AUC_R3","AUC_R4","AUC_R5","AUC_R6","AUC_R7","AUC_R8","AUC_R9","AUC_A1","AUC_A2","AUC_A3","AUC_A4","AUC_A5","AUC_A6","AUC_A7","AUC_A8","AUC_A9","AUC_A10","AUC_A11","AUC_A12","AUC_A13","AUC_A14","AUC_A15","AUC_A17","AUC_A18","NVS_NR_bER_AC50","NVS_NR_hER_AC50","NVS_NR_mERa_AC50","OT_ER_ERaERa_0480_AC50","OT_ER_ERaERa_1440_AC50","OT_ER_ERaERb_0480_AC50","OT_ER_ERaERb_1440_AC50","OT_ER_ERbERb_0480_AC50","OT_ER_ERbERb_1440_AC50","OT_ERa_EREGFP_0120_AC50","OT_ERa_EREGFP_0480_AC50","ATG_ERa_TRANS_up_AC50","ATG_ERE_CIS_up_AC50","Tox21_ERa_BLA_Agonist_ratio_AC50","Tox21_ERa_LUC_BG1_Agonist_AC50","ACEA_T47D_80hr_Positive_AC50","Tox21_ERa_BLA_Antagonist_ratio_AC50","Tox21_ERa_LUC_BG1_Antagonist_AC50","NVS_NR_bER_Emax","NVS_NR_hER_Emax","NVS_NR_mERa_Emax","OT_ER_ERaERa_0480_Emax","OT_ER_ERaERa_1440_Emax","OT_ER_ERaERb_0480_Emax","OT_ER_ERaERb_1440_Emax","OT_ER_ERbERb_0480_Emax","OT_ER_ERbERb_1440_Emax","OT_ERa_EREGFP_0120_Emax","OT_ERa_EREGFP_0480_Emax","ATG_ERa_TRANS_up_Emax","ATG_ERE_CIS_up_Emax","Tox21_ERa_BLA_Agonist_ratio_Emax","Tox21_ERa_LUC_BG1_Agonist_Emax","ACEA_T47D_80hr_Positive_Emax","Tox21_ERa_BLA_Antagonist_ratio_Emax","Tox21_ERa_LUC_BG1_Antagonist_Emax","NVS_NR_bER_T","NVS_NR_hER_T","NVS_NR_mERa_T","OT_ER_ERaERa_0480_T","OT_ER_ERaERa_1440_T","OT_ER_ERaERb_0480_T","OT_ER_ERaERb_1440_T","OT_ER_ERbERb_0480_T","OT_ER_ERbERb_1440_T","OT_ERa_EREGFP_0120_T","OT_ERa_EREGFP_0480_T","ATG_ERa_TRANS_up_T","ATG_ERE_CIS_up_T","Tox21_ERa_BLA_Agonist_ratio_T","Tox21_ERa_LUC_BG1_Agonist_T","ACEA_T47D_80hr_Positive_T","Tox21_ERa_BLA_Antagonist_ratio_T","Tox21_ERa_LUC_BG1_Antagonist_T","NVS_NR_bER_W","NVS_NR_hER_W","NVS_NR_mERa_W","OT_ER_ERaERa_0480_W","OT_ER_ERaERa_1440_W","OT_ER_ERaERb_0480_W","OT_ER_ERaERb_1440_W","OT_ER_ERbERb_0480_W","OT_ER_ERbERb_1440_W","OT_ERa_EREGFP_0120_W","OT_ERa_EREGFP_0480_W","ATG_ERa_TRANS_up_W","ATG_ERE_CIS_up_W","Tox21_ERa_BLA_Agonist_ratio_W","Tox21_ERa_LUC_BG1_Agonist_W","ACEA_T47D_80hr_Positive_W","Tox21_ERa_BLA_Antagonist_ratio_W","Tox21_ERa_LUC_BG1_Antagonist_W","NVS_NR_bER_Zscore","NVS_NR_hER_Zscore","NVS_NR_mERa_Zscore","OT_ER_ERaERa_0480_Zscore","OT_ER_ERaERa_1440_Zscore","OT_ER_ERaERb_0480_Zscore","OT_ER_ERaERb_1440_Zscore","OT_ER_ERbERb_0480_Zscore","OT_ER_ERbERb_1440_Zscore","OT_ERa_EREGFP_0120_Zscore","OT_ERa_EREGFP_0480_Zscore","ATG_ERa_TRANS_up_Zscore","ATG_ERE_CIS_up_Zscore","Tox21_ERa_BLA_Agonist_ratio_Zscore","Tox21_ERa_LUC_BG1_Agonist_Zscore","ACEA_T47D_80hr_Positive_Zscore","Tox21_ERa_BLA_Antagonist_ratio_Zscore","Tox21_ERa_LUC_BG1_Antagonist_Zscore","NVS_NR_bER_maxConc","NVS_NR_hER_maxConc","NVS_NR_mERa_maxConc","OT_ER_ERaERa_0480_maxConc","OT_ER_ERaERa_1440_maxConc","OT_ER_ERaERb_0480_maxConc","OT_ER_ERaERb_1440_maxConc","OT_ER_ERbERb_0480_maxConc","OT_ER_ERbERb_1440_maxConc","OT_ERa_EREGFP_0120_maxConc","OT_ERa_EREGFP_0480_maxConc","ATG_ERa_TRANS_up_maxConc","ATG_ERE_CIS_up_maxConc","Tox21_ERa_BLA_Agonist_ratio_maxConc","Tox21_ERa_LUC_BG1_Agonist_maxConc","ACEA_T47D_80hr_Positive_maxConc","Tox21_ERa_BLA_Antagonist_ratio_maxConc","Tox21_ERa_LUC_BG1_Antagonist_maxConc","NVS_NR_bER_AC10","NVS_NR_hER_AC10","NVS_NR_mERa_AC10","OT_ER_ERaERa_0480_AC10","OT_ER_ERaERa_1440_AC10","OT_ER_ERaERb_0480_AC10","OT_ER_ERaERb_1440_AC10","OT_ER_ERbERb_0480_AC10","OT_ER_ERbERb_1440_AC10","OT_ERa_EREGFP_0120_AC10","OT_ERa_EREGFP_0480_AC10","ATG_ERa_TRANS_up_AC10","ATG_ERE_CIS_up_AC10","Tox21_ERa_BLA_Agonist_ratio_AC10","Tox21_ERa_LUC_BG1_Agonist_AC10","ACEA_T47D_80hr_Positive_AC10","Tox21_ERa_BLA_Antagonist_ratio_AC10","Tox21_ERa_LUC_BG1_Antagonist_AC10","NVS_NR_bER_ACC","NVS_NR_hER_ACC","NVS_NR_mERa_ACC","OT_ER_ERaERa_0480_ACC","OT_ER_ERaERa_1440_ACC","OT_ER_ERaERb_0480_ACC","OT_ER_ERaERb_1440_ACC","OT_ER_ERbERb_0480_ACC","OT_ER_ERbERb_1440_ACC","OT_ERa_EREGFP_0120_ACC","OT_ERa_EREGFP_0480_ACC","ATG_ERa_TRANS_up_ACC","ATG_ERE_CIS_up_ACC","Tox21_ERa_BLA_Agonist_ratio_ACC","Tox21_ERa_LUC_BG1_Agonist_ACC","ACEA_T47D_80hr_Positive_ACC","Tox21_ERa_BLA_Antagonist_ratio_ACC","Tox21_ERa_LUC_BG1_Antagonist_ACC","NVS_NR_bER_ACB","NVS_NR_hER_ACB","NVS_NR_mERa_ACB","OT_ER_ERaERa_0480_ACB","OT_ER_ERaERa_1440_ACB","OT_ER_ERaERb_0480_ACB","OT_ER_ERaERb_1440_ACB","OT_ER_ERbERb_0480_ACB","OT_ER_ERbERb_1440_ACB","OT_ERa_EREGFP_0120_ACB","OT_ERa_EREGFP_0480_ACB","ATG_ERa_TRANS_up_ACB","ATG_ERE_CIS_up_ACB","Tox21_ERa_BLA_Agonist_ratio_ACB","Tox21_ERa_LUC_BG1_Agonist_ACB","ACEA_T47D_80hr_Positive_ACB","Tox21_ERa_BLA_Antagonist_ratio_ACB","Tox21_ERa_LUC_BG1_Antagonist_ACB","NVS_NR_bER_flags","NVS_NR_hER_flags","NVS_NR_mERa_flags","OT_ER_ERaERa_0480_flags","OT_ER_ERaERa_1440_flags","OT_ER_ERaERb_0480_flags","OT_ER_ERaERb_1440_flags","OT_ER_ERbERb_0480_flags","OT_ER_ERbERb_1440_flags","OT_ERa_EREGFP_0120_flags","OT_ERa_EREGFP_0480_flags","ATG_ERa_TRANS_up_flags","ATG_ERE_CIS_up_flags","Tox21_ERa_BLA_Agonist_ratio_flags","Tox21_ERa_LUC_BG1_Agonist_flags","ACEA_T47D_80hr_Positive_flags","Tox21_ERa_BLA_Antagonist_ratio_flags","Tox21_ERa_LUC_BG1_Antagonist_flags","pseudo_AC50_median","pseudo_AC50_min","AC50_spread","pseudo_AC10_median","pseudo_AC10_min","pseudo_ACC_median","pseudo_ACC_min","pseudo_ACB_median","pseudo_ACB_min","maximum_receptor","EAS_R1","EAS_R1_Class","EAS_R2","EAS_R2_Class","N_assays_tested","N_assays_hit","N_assays_hit_hi_Z","N_assays_hit_lo_Z","promiscuity_hi_Z","promiscuity_lo_Z","median_T","median_Z","Lit_N_Binding","Lit_N_Agonist","Lit_N_Antagonist","Lit_Hit_Binding","Lit_Hit_Agonist","Lit_Hit_Antagonist","ATG_nonER_hits_HIZ_TRANS","ATG_nonER_hits_HIZ_CIS","NVS_nonER_hits_HIZ","Tox21_BLA_Agonist_nonER_hits_HIZ","Tox21_BLA_Antagonist_nonER_hits_HIZ","Tox21_LUC_Agonist_nonER_hits_HIZ","Tox21_LUC_Antagonist_nonER_hits_HIZ","mol_MW","dipole","SASA","FOSA","FISA","PISA","WPSA","volume","donorHB","accptHB","dip_2_V","ACxDN_5_SA","glob","QPpolrz","QPlogPC16","QPlogPoct","QPlogPw","QPlogPo_w","QPlogS","CIQPlogS","QPlogHERG","QPPCaco","QPlogBB","QPPMDCK","QPlogKp","IP_eV","EA_eV","X_metab","QPlogKhsa","HumanOralAbsorption","PercentHumanOralAbsorption","SAfluorine","SAamideO","PSA","RuleOfFive","RuleOfThree","Molecular_weight","passesRuleOfThree","species","numRo5Violations","rotatableBonds","molecularWeight","alogp","acdAcidicPka","acdBasicPka","acdLogp","acdLogd","AM1_dipole","AM1_HOMO","AM1_LUMO","electrophilicity_index","DFT_IP","DFT_EA","DFT_electron_negativity","DFT_hardness","DFT_electrophilicity","DFT_donatingpower","DFT_acceptingpower","DFT_dipole","DFT_polarizability","DFT_aqueous_electron_affnity","DFT_HOMO","DFT_LUMO","Charged"};
	
	public static final String lastUpdated = "04/14/2021";//email from richard judson
	public static final String sourceName = ScoreRecord.strSourceCERAPP_Exp;
	
	private static final String fileName = "S2 ER SuperMatrix 2015-03-24.xlsx";
	
	public static Vector<JsonObject> parseCERAPP_ExpRecordsFromExcel() {
		String mainFolderPath="AA Dashboard\\Data";
		ExcelSourceReader esr = new ExcelSourceReader(fileName, mainFolderPath,sourceName);
		
//		esr.createClassTemplateFiles();		
		
		HashMap<Integer,String> hm = esr.generateDefaultMap(fieldNames, 0);
		Vector<JsonObject> records = esr.parseRecordsFromExcel(hm, 0,true);
		return records;
	}
	
	
	public static void main(String[] args) {
		Vector<JsonObject> records =parseCERAPP_ExpRecordsFromExcel();
		
		Gson gson= new Gson();
		for (JsonObject record:records) {
			
			
			RecordCERAPP_Exp r = gson.fromJson(record.toString(),RecordCERAPP_Exp.class);
			
			System.out.println(r.CASRN+"\t"+r.AUC_Agonist+"\t"+r.AUC_Antagonist);
		}
		
	}
	
}
